name: ci

on:
  push:
    branches: [master]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: juarezer7c
          password: 3cc777bb-3684-42d0-a735-e4ef8aa1ff3c
